name: Node.js

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '18' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install --save-dev
      - name: Minify with rollup
        run: make minify
      - name: Upload minified code as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist # Or your Rollup output directory
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/* # Upload files from your build output
